typedef struct Processor {
	Object _contextActorUID;
	Object _contextJobName;
	Object _contextJobStageName;
	Object _machine;
	Object _localNamespaces;
	Object _commandSystem;
	Object _contextMessages;
	Object _processorCodes;
} *Processor;

Object Processor_Create(void);
Object Processor_Clone(Object _self);
Object Processor_DeepClone(Object _self);
Object Processor_Destroy(Object _self);
Object Processor_Compare(Object _self, Object _processor);
Object Processor_SetMachine(Object _self, Object _machine);
Object Processor_ContextActorUID(Object _self);
Object Processor_ContextJobName(Object _self);
Object Processor_ContextJobStageName(Object _self);
Object Processor_ContextActor(Object _self);
Object Processor_ContextJob(Object _self);
Object Processor_ContextJobStage(Object _self);
Object Processor_Init(Object _self);
Object Processor_DefineActorMethod(Object _self, Object _method, Object _methodName);
Object Processor_DefineActorMethodWithBody(Object _self, Object _methodBody, Object _methodName);
Object Processor_UnDefineMethod(Object _self, Object _methodName);
Object Processor_UnDefineActorMethod(Object _self, Object _methodName);
Object Processor_DefineJobMethod(Object _self, Object _method, Object _methodName);
Object Processor_DefineJobMethodWithBody(Object _self, Object _methodBody, Object _methodName);
Object Processor_UnDefineJobMethod(Object _self, Object _methodName);
Object Processor_DefineFieldInNameSpaceWithUID(Object _self, Object _fieldName, Object _nameSpace, Object _uid);
Object Processor_SetField(Object _self, Object _fieldName, Object _uid);
Object Processor_UniteField(Object _self, Object _destinationFieldName, Object _sourceFieldName);
Object Processor_UnDefineFieldInNamespace(Object _self, Object _fieldName, Object _locationType);
Object Processor_AddJobWithName(Object _self, Object _job, Object _jobName);
Object Processor_FinishThisJob(Object _self);
Object Processor_AddJobStage(Object _self, Object _jobStage, Object _jobStageName);
Object Processor_BlockStage(Object _self, Object _stageName);
Object Processor_UnBlockStage(Object _self, Object _stageName);
Object Processor_RemoveJobStage(Object _self, Object _jobStageName);
Object Processor_RemoveAllStages(Object _self);
Object Processor_AddMessageSlot(Object _self, Object _messageSlot, Object _messageSlotName);
Object Processor_BlockMessageSlot(Object _self, Object _messageSlotName);
Object Processor_UnBlockMessageSlot(Object _self, Object _messageSlotName);
Object Processor_RemoveMessageSlot(Object _self, Object _messageSlotName);
Object Processor_RemoveAllMessageSlots(Object _self);
Object Processor_AttachToStageMessageSlot(Object _self, Object _stageName, Object _messageName);
Object Processor_RemoveAllStagesAndMessageSlots(Object _self);
Object Processor_RemoveMessageInMessageSlot(Object _self, Object _messageSlotName);
Object Processor_RemoveAllMessagesOfCurrentStageForCurrentStage(Object _self);
Object Processor_RemoveAllMessagesOfCurrentStageForAllStages(Object _self);
Object Processor_RemoveAllMessagesOfAllOpenedStages(Object _self);
Object Processor_RemoveAllReceivedMessages(Object _self);
Object Processor_AddJobStageInJob(Object _self, Object _jobStage, Object _jobStageName, Object _jobName);
Object Processor_BlockStageInJob(Object _self, Object _stageName, Object _jobName);
Object Processor_UnBlockStageInJob(Object _self, Object _stageName, Object _jobName);
Object Processor_RemoveJobStageInJob(Object _self, Object _jobStageName, Object _jobName);
Object Processor_RemoveAllStagesInJob(Object _self, Object _jobName);
Object Processor_AddMessageSlotInJob(Object _self, Object _messageSlot, Object _messageSlotName, Object _jobName);
Object Processor_BlockMessageSlotInJob(Object _self, Object _messageSlotName, Object _jobName);
Object Processor_UnBlockMessageSlotInJob(Object _self, Object _messageSlotName, Object _jobName);
Object Processor_RemoveMessageSlotInJob(Object _self, Object _messageSlotName, Object _jobName);
Object Processor_RemoveAllMessageSlotsInJob(Object _self, Object _jobName);
Object Processor_AttachToStageMessageSlotInJob(Object _self, Object _stageName, Object _messageName, Object _jobName);
Object Processor_RemoveAllStagesAndMessageSlotsInJob(Object _self, Object _jobName);
Object Processor_RemoveMessageInMessageSlotInJob(Object _self, Object _messageSlotName, Object _jobName);
Object Processor_RemoveAllMessagesOfCurrentStageForCurrentStageInJob(Object _self, Object _jobName);
Object Processor_RemoveAllMessagesOfCurrentStageForAllStagesInJob(Object _self, Object _jobName);
Object Processor_RemoveAllMessagesOfAllOpenedStagesInJob(Object _self, Object _jobName);
Object Processor_RemoveAllReceivedMessagesInJob(Object _self, Object _jobName);
Object Processor_CreateStageRequestEntityBasicMethodInJob(Object _self, Object _requestName, Object _entity, Object _basicMethod, Object _job);
Object Processor_CreateStageReplyEntityBasicMethodInJob(Object _self, Object _requestName, Object _entity, Object _basicMethod, Object _job);
Object Processor_CreateStageEmptyEntityBasicMethodInJob(Object _self, Object _requestName, Object _entity, Object _basicMethod, Object _job);
Object Processor_DefineFieldHelper(Object _self, Object _uid, Object _fieldName, Object _nameSpace);
Object Processor_EntityFromNamedMessageField(Object _self, Object _messageName, Object _fieldName);
Object Processor_NamespaceNameToNamespace(Object _self, Object _locationType);
Object Processor_FieldNameToNamespaceName(Object _self, Object _fieldName);
Object Processor_FieldNameToSynonim(Object _self, Object _fieldName);
Object Processor_FieldNameToUIDInJobActor(Object _self, Object _fieldName, Object _job, Object _actor);
Object Processor_FieldNameToUID(Object _self, Object _fieldName);
Object Processor_MessageInMessageSlot(Object _self, Object _messageSlotName);
Object Processor_SendMessage(Object _self, Object _message);
Object Processor_SendMessageToMessageField(Object _self, Object _message, Object _messageSlotName, Object _fieldName);
Object Processor_SendReplyForMessage(Object _self, Object _replyMessage, Object _messageSlotName);
Object Processor_InvokeMethodWithParameters(Object _self, Object _methodName, Object _parameters);
Object Processor_MessageConfirmsToParameterInJobActor(Object _self, Object _message, Object _parameter, Object _job, Object _actor);
Object Processor_TryLinkMessageWithMessageSlotInJobActor(Object _self, Object _message, Object _messageSlot, Object _job, Object _actor, Object _messageSlotName, Object _jobName);
Object Processor_ProcessMessageForActor(Object _self, Object _message, Object _actor);
Object Processor_ProcessOneJobIfAny(Object _self);
Object Processor_ProcessUID(Object _self, Object _uid);
