typedef struct Processor {
	Object _contextObject;
	Object _contextJobStage;
	Object _contextJob;
	Object _machine;
	Object _localNamespaces;
	Object _helperStack;
	Object _processorCodes;
} *Processor;

Object Processor_Create(void);
Object Processor_Clone(Object _self);
Object Processor_DeepClone(Object _self);
Object Processor_Destroy(Object _self);
Object Processor_Compare(Object _self, Object _processor);
Object Processor_SetMachine(Object _self, Object _machine);
Object Processor_Init(Object _self);
Object Processor_Do(Object _self, Object _toDo);
Object Processor_DoCode(Object _self, Object _toDo);
Object Processor_FieldNameToSynonimCode(Object _self, Object _toDo);
Object Processor_SynonimToUIDCode(Object _self, Object _toDo);
Object Processor_AddCurrentObjectToStackCode(Object _self, Object _toDo);
Object Processor_AddCurrentJobToStackCode(Object _self, Object _toDo);
Object Processor_AddCurrentJobStageToStackCode(Object _self, Object _toDo);
Object Processor_AddListToStackCode(Object _self, Object _toDo);
Object Processor_AddListMapToStackCode(Object _self, Object _toDo);
Object Processor_PopFromStackCode(Object _self, Object _toDo);
Object Processor_AddObjectToListMapCode(Object _self, Object _toDo);
Object Processor_AddObjectToListCode(Object _self, Object _toDo);
Object Processor_AddObjectToStackCode(Object _self, Object _toDo);
Object Processor_DuplicateTopInStackCode(Object _self, Object _toDo);
Object Processor_SwapTopInStackCode(Object _self, Object _toDo);
Object Processor_SendMessageCode(Object _self, Object _toDo);
Object Processor_InvokeMethodCode(Object _self, Object _toDo);
Object Processor_DefineMethodCode(Object _self, Object _toDo);
Object Processor_UnDefineMethodCode(Object _self, Object _toDo);
Object Processor_DefineLocalFieldCode(Object _self, Object _toDo);
Object Processor_DefineJobFieldCode(Object _self, Object _toDo);
Object Processor_DefineObjectFieldCode(Object _self, Object _toDo);
Object Processor_DefineGlobalFieldCode(Object _self, Object _toDo);
Object Processor_SetFieldCode(Object _self, Object _toDo);
Object Processor_UniteFieldCode(Object _self, Object _toDo);
Object Processor_UnDefineFieldCode(Object _self, Object _toDo);
Object Processor_AddJobToObjectCode(Object _self, Object _toDo);
Object Processor_AddStageToJobCode(Object _self, Object _toDo);
Object Processor_AddConditionToStageCode(Object _self, Object _toDo);
Object Processor_RemoveAllStagesCode(Object _self, Object _toDo);
Object Processor_FinishJobCode(Object _self, Object _toDo);
Object Processor_LocationType(Object _self, Object _objectName);
Object Processor_ResolveName(Object _self, Object _objectName);
Object Processor_SendMessage(Object _self, Object _message);
Object Processor_InvokeMethod(Object _self, Object _methodName, Object _parameters);
Object Processor_MessageConfirmsToParameter(Object _self, Object _message, Object _parameter);
Object Processor_TryLinkMessageWithJobStage(Object _self, Object _jobStage, Object _message);
Object Processor_ProcessOneMessage(Object _self);
Object Processor_ProcessOneJobIfAny(Object _self);
Object Processor_ProcessObject(Object _self, Object _uid);
