typedef struct Processor {
	Object _contextUID;
	Object _contextJobName;
	Object _contextJobStageName;
	Object _machine;
	Object _localNamespaces;
	Object _helperStack;
	Object _processorCodes;
} *Processor;

Object Processor_Create(void);
Object Processor_Clone(Object _self);
Object Processor_DeepClone(Object _self);
Object Processor_Destroy(Object _self);
Object Processor_Compare(Object _self, Object _processor);
Object Processor_SetMachine(Object _self, Object _machine);
Object Processor_ContextObject(Object _self);
Object Processor_ContextJob(Object _self);
Object Processor_ContextJobStage(Object _self);
Object Processor_Init(Object _self);
Object Processor_Do(Object _self, Object _toDo);
Object Processor_GetNamedEntityFromToDoOrStack(Object _self, Object _entityName, Object _toDo);
Object Processor_DoCode(Object _self, Object _toDo);
Object Processor_EntityFromMessageFieldCode(Object _self, Object _toDo);
Object Processor_UIDFromFieldCode(Object _self, Object _toDo);
Object Processor_AddCurrentUIDToStackCode(Object _self, Object _toDo);
Object Processor_AddCurrentJobToStackCode(Object _self, Object _toDo);
Object Processor_AddCurrentJobStageToStackCode(Object _self, Object _toDo);
Object Processor_AddListToStackCode(Object _self, Object _toDo);
Object Processor_AddListMapToStackCode(Object _self, Object _toDo);
Object Processor_RemoveFromStackCode(Object _self, Object _toDo);
Object Processor_AddEntityToListMapCode(Object _self, Object _toDo);
Object Processor_RemoveEntityFromListMapByKeyCode(Object _self, Object _toDo);
Object Processor_RemoveEntityFromListMapByValueCode(Object _self, Object _toDo);
Object Processor_AddEntityToListCode(Object _self, Object _toDo);
Object Processor_RemoveEntityFromListByPositionCode(Object _self, Object _toDo);
Object Processor_RemoveEntityFromListByValueCode(Object _self, Object _toDo);
Object Processor_AddEntityToStackCode(Object _self, Object _toDo);
Object Processor_DuplicateTopInStackCode(Object _self, Object _toDo);
Object Processor_SwapTopInStackCode(Object _self, Object _toDo);
Object Processor_SendMessageToUIDCode(Object _self, Object _toDo);
Object Processor_SendMessageToFieldCode(Object _self, Object _toDo);
Object Processor_SendReplyForMessageCode(Object _self, Object _toDo);
Object Processor_InvokeMethodCode(Object _self, Object _toDo);
Object Processor_DefineMethodCode(Object _self, Object _toDo);
Object Processor_UnDefineMethodCode(Object _self, Object _toDo);
Object Processor_DefineLocalFieldCode(Object _self, Object _toDo);
Object Processor_DefineJobFieldCode(Object _self, Object _toDo);
Object Processor_DefineObjectFieldCode(Object _self, Object _toDo);
Object Processor_DefineGlobalFieldCode(Object _self, Object _toDo);
Object Processor_DefineFieldHelper(Object _self, Object _toDo, Object _nameSpace);
Object Processor_SetFieldCode(Object _self, Object _toDo);
Object Processor_UniteFieldCode(Object _self, Object _toDo);
Object Processor_UnDefineFieldCode(Object _self, Object _toDo);
Object Processor_AddJobCode(Object _self, Object _toDo);
Object Processor_AddJobStageCode(Object _self, Object _toDo);
Object Processor_AddMessageSlotCode(Object _self, Object _toDo);
Object Processor_RemoveJobStageCode(Object _self, Object _toDo);
Object Processor_RemoveMessageSlotCode(Object _self, Object _toDo);
Object Processor_RemoveMessageInSlotCode(Object _self, Object _toDo);
Object Processor_RemoveAllReceivedMessagesCode(Object _self, Object _toDo);
Object Processor_RemoveAllJobStagesCode(Object _self, Object _toDo);
Object Processor_RemoveAllMessageSlotsCode(Object _self, Object _toDo);
Object Processor_RemoveAllJobStagesAndMessageSlotsCode(Object _self, Object _toDo);
Object Processor_AttachToStageMessageSlotCode(Object _self, Object _toDo);
Object Processor_FinishThisJobCode(Object _self, Object _toDo);
Object Processor_AttachToStageMessageSlot(Object _self, Object _stageName, Object _messageName);
Object Processor_EntityFromNamedMessageField(Object _self, Object _messageName, Object _fieldName);
Object Processor_NamespaceNameToNamespace(Object _self, Object _locationType);
Object Processor_FieldNameToNamespaceName(Object _self, Object _fieldName);
Object Processor_FieldNameToSynonim(Object _self, Object _fieldName);
Object Processor_FieldNameToUID(Object _self, Object _fieldName);
Object Processor_SendMessage(Object _self, Object _message);
Object Processor_SendReplyForMessage(Object _self, Object _replyMessage, Object _messageSlotName);
Object Processor_InvokeMethodWithParameters(Object _self, Object _methodName, Object _parameters);
Object Processor_MessageConfirmsToParameter(Object _self, Object _message, Object _parameter);
Object Processor_TryLinkMessageWithMessageSlotAndJob(Object _self, Object _message, Object _messageSlot, Object _job);
Object Processor_ProcessMessageForObject(Object _self, Object _message, Object _object);
Object Processor_ProcessOneJobIfAny(Object _self);
Object Processor_ProcessUID(Object _self, Object _uid);
