typedef struct ListMap {
	Object _root;
	Object _underClonning;
} *ListMap;

Object ListMap_Create(void);
Object ListMap_Init(Object _self);
Object ListMap_Compare(Object _self, Object _listMap);
Object ListMap_Destroy(Object _self);
Object ListMap_Clone(Object _self);
Object ListMap_DeepClone(Object _self);
Object ListMap_Empty(Object _self);
Object ListMap_Add(Object _self, Object _list, Object _object);
Object ListMap_AddListMap(Object _self, Object _listMap);
Object ListMap_Remove(Object _self, Object _list);
Object ListMap_RemoveAll(Object _self);
Object ListMap_ResetWithListMapDestructive(Object _self, Object _listMap);
Object ListMap_RemoveKeyWithConfirmation(Object _self, Object _list);
Object ListMap_ObjectAt(Object _self, Object _list);
Object ListMap_Contains(Object _self, Object _list);
Object ListMap_ListMapAt(Object _self, Object _list);
Object ListMap_ListAt(Object _self, Object _list);
Object ListMap_QueueAt(Object _self, Object _list);
Object ListMap_LogicAt(Object _self, Object _list);
Object ListMap_NumberAt(Object _self, Object _list);
Object ListMap_SynonimAt(Object _self, Object _list);
Object ListMap_MethodAt(Object _self, Object _list);
Object ListMap_First(Object _self);
Object ListMap_Last(Object _self);
Object ListMap_Size(Object _self);
Object ListMap_DumpKeys(Object _self);
Object ListMap_DumpListToListMap(Object _self);
Object ListMap_ActorMethods(Object _self);
Object ListMap_ActorFields(Object _self);
Object ListMap_ActorJobs(Object _self);
Object ListMap_ActorJobsIterator(Object _self);
Object ListMap_ActorProperties(Object _self);
Object ListMap_ActorField(Object _self, Object _fieldName);
Object ListMap_ActorFieldUID(Object _self, Object _fieldName);
Object ListMap_ActorMethod(Object _self, Object _methodName);
Object ListMap_ActorRemoveMethod(Object _self, Object _methodName);
Object ListMap_ActorSetMethod(Object _self, Object _method, Object _methodName);
Object ListMap_ActorSetMethodBody(Object _self, Object _methodBody, Object _methodName);
Object ListMap_ActorSetBasicMethod(Object _self, Object _entity, Object _basicMethod, Object _methodName);
Object ListMap_ActorSetJob(Object _self, Object _job, Object _jobName);
Object ListMap_ActorSetProperty(Object _self, Object _value, Object _propertyName);
Object ListMap_ActorRemoveJob(Object _self, Object _jobName);
Object ListMap_ActorResetMethodsDestructive(Object _self, Object _newMethods);
Object ListMap_ActorResetFieldsDestructive(Object _self, Object _newFields);
Object ListMap_ActorResetJobsDestructive(Object _self, Object _newJobs);
Object ListMap_ActorRemoveAllIdentifiers(Object _self);
Object ListMap_ActorJob(Object _self, Object _jobName);
Object ListMap_ActorProperty(Object _self, Object _propertyName);
Object ListMap_ActorNotificationRequests(Object _self);
Object ListMap_ActorAddNotificationRequest(Object _self, Object _notificationRequest);
Object ListMap_ActorNotificationRequestsIterator(Object _self);
Object ListMap_JobStages(Object _self);
Object ListMap_JobMessageSlots(Object _self);
Object ListMap_JobStage(Object _self, Object _stageName);
Object ListMap_JobFieldInMessageSlot(Object _self, Object _fieldName, Object _messageSlotName);
Object ListMap_JobMessageSlot(Object _self, Object _messageSlotName);
Object ListMap_JobMessageInMessageSlot(Object _self, Object _messageSlotName);
Object ListMap_JobSetStage(Object _self, Object _stage, Object _stageName);
Object ListMap_JobRemoveStage(Object _self, Object _stageName);
Object ListMap_JobRemoveStageAndMessageSlots(Object _self, Object _stageName);
Object ListMap_JobSetMessageSlot(Object _self, Object _messageSlot, Object _messageSlotName);
Object ListMap_JobRemoveMessageSlot(Object _self, Object _messageSlotName);
Object ListMap_JobMessageSlotsIterator(Object _self);
Object ListMap_JobStagesIterator(Object _self);
Object ListMap_JobRemoveAllStages(Object _self);
Object ListMap_JobRemoveAllMessageSlots(Object _self);
Object ListMap_JobCreateStageWithNameMethodRequestMessageSlot(Object _self, Object _stageName, Object _methodName, Object _messageSlotName, Object _messageSlotRequestName);
Object ListMap_JobCreateStageWithNameMethodMessageSlotNameAndEntity(Object _self, Object _stageName, Object _methodName, Object _messageSlotName, Object _messageSlot);
Object ListMap_MessageSender(Object _self);
Object ListMap_MessageReceiver(Object _self);
Object ListMap_MessageType(Object _self);
Object ListMap_MessageRequest(Object _self);
Object ListMap_MessageSetSender(Object _self, Object _sender);
Object ListMap_MessageSetReceiver(Object _self, Object _receiver);
Object ListMap_MessageSetType(Object _self, Object _type);
Object ListMap_MessageSetTypeReply(Object _self);
Object ListMap_MessageSetTypeRequest(Object _self);
Object ListMap_MessageSetTypeNotification(Object _self);
Object ListMap_MessageSetRequest(Object _self, Object _request);
Object ListMap_MessageSetReply(Object _self, Object _reply);
Object ListMap_MessageSetReplySuccess(Object _self);
Object ListMap_MessageSetReplyFail(Object _self);
Object ListMap_MessageReply(Object _self);
Object ListMap_MessageReplyIsSuccess(Object _self);
Object ListMap_MessageReplyIsFail(Object _self);
Object ListMap_MessageSetJobNameAndMessageSlotName(Object _self, Object _jobName, Object _messageSlotName);
Object ListMap_MessageAttributesMessageSlots(Object _self);
Object ListMap_MessageSlotStages(Object _self);
Object ListMap_MessageSlotStagesIterator(Object _self);
Object ListMap_MessageSlotMessage(Object _self);
Object ListMap_MessageSlotMessages(Object _self);
Object ListMap_MessageSlotSetMessage(Object _self, Object _message);
Object ListMap_MessageSlotRemoveMessage(Object _self, Object _message);
Object ListMap_MessageSlotRemoveAllMessages(Object _self);
Object ListMap_MessageSlotField(Object _self, Object _fieldName);
Object ListMap_MessageSlotSetStage(Object _self, Object _stageName);
Object ListMap_MessageSlotConditions(Object _self);
Object ListMap_MessageSlotSetCondition(Object _self, Object _condition);
Object ListMap_MessageSlotIsBlocked(Object _self);
Object ListMap_MessageSlotIsClosed(Object _self);
Object ListMap_MessageSlotIsOpened(Object _self);
Object ListMap_MessageSlotBlock(Object _self);
Object ListMap_MessageSlotOpen(Object _self);
Object ListMap_MessageSlotClose(Object _self);
Object ListMap_StageContainsMessageSlot(Object _self, Object _messageSlotName);
Object ListMap_StageSetMethod(Object _self, Object _methodName);
Object ListMap_StageSetMessageSlot(Object _self, Object _messageSlotName);
Object ListMap_StageMessageSlots(Object _self);
Object ListMap_StageMessageSlotsIterator(Object _self);
Object ListMap_StageMethod(Object _self);
Object ListMap_StageIncrementMessagesCounter(Object _self);
Object ListMap_StageDecrementMessagesCounter(Object _self);
Object ListMap_StageMessagesCounter(Object _self);
Object ListMap_StageSetMessagesCounter(Object _self, Object _newMessagesCounter);
Object ListMap_StageSetBlocked(Object _self);
Object ListMap_StageSetReady(Object _self);
Object ListMap_StageSetWaiting(Object _self);
Object ListMap_StageIsWaiting(Object _self);
Object ListMap_StageIsReady(Object _self);
Object ListMap_StageIsBlocked(Object _self);
