typedef struct ListIterator {
	Object list;
	Object node;
} *ListIterator;
Object ListIterator_Compare(Object self, Object iterator);
Object ListIterator_Destroy(Object self);
Object ListIterator_Clone(Object self);
Object ListIterator_InitWithNodeAndList(Object self, Object list, Object node);
Object ListIterator_ResetNode(Object self, Object node);
Object ListIterator_Hide(Object self);
Object ListIterator_Next(Object self);
Object ListIterator_Prev(Object self);
Object ListIterator_ToBegin(Object self);
Object ListIterator_ToEnd(Object self);
Object ListIterator_ToPosition(Object self, Object position);
Object ListIterator_FromPositionToPosition(Object self, Object positionFrom, Object positionTo);
Object ListIterator_SearchForward(Object self, Object object);
Object ListIterator_SearchForwardOffset(Object self, Object object);
Object ListIterator_ThisRemove(Object self);
Object ListIterator_PrevRemove(Object self);
Object ListIterator_NextRemove(Object self);
Object ListIterator_ThisData(Object self);
Object ListIterator_NextData(Object self);
Object ListIterator_PrevData(Object self);
Object ListIterator_ThisSetData(Object self, Object object);
Object ListIterator_PrevSetData(Object self, Object object);
Object ListIterator_NextSetData(Object self, Object object);
Object ListIterator_AddAfter(Object self, Object object);
Object ListIterator_AddBefore(Object self, Object object);
Object ListIterator_ThisBegin(Object self);
Object ListIterator_ThisEnd(Object self);
Object ListIterator_PrevBegin(Object self);
Object ListIterator_NextEnd(Object self);
Object ListIterator_AddListBefore(Object self, Object list);
Object ListIterator_AddListAfter(Object self, Object list);
Object ListIterator_RemoveCount(Object self, Object count);
