Object List_Init(Object self);
Object List_Destroy(Object self);
Object List_Clone(Object self);
Object List_Compare(Object self, Object list);
Object List_Clean(Object self);
Object List_PushBack(Object self, Object object);
Object List_PushFront(Object self, Object object);
Object List_AddAfterPosition(Object self, Object position, Object object);
Object List_AddBeforePosition(Object self, Object position, Object object);
Object List_RemoveFirst(Object self, Object object);
Object List_Last(Object self);
Object List_First(Object self);
Object List_SystemIterator(Object self);
Object List_DataFromPosition(Object self, Object position);
Object List_Search(Object self, Object object);
Object List_IteratorFromPosition(Object self, Object position);
Object List_CreatingIteratorFromPosition(Object self, Object position);
Object List_SearchPositions(Object self, Object object);
Object List_SublistBetweenPositions(Object self, Object positionFrom, Object positionTo);
Object List_SublistBetweenIterators(Object self, Object positionFrom, Object positionTo);
Object List_Size(Object self);
Object List_Concatenate(Object self, Object list);
